# Generated by Django 5.0.4 on 2024-04-16 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Mango',
        ),
    ]
