# Generated by Django 5.0.4 on 2024-04-18 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
